services:
    
  prestashop.module.inl_shippingcost:
    class: Inl_shippingcost
    factory: [Module, getInstanceByName]
    arguments:
      - 'inl_shippingcost'

  prestashop.module.inl_shippingcost.repository.carrier_rule_repository:
    class: PrestaShop\Module\Inl_shippingcost\Repository\CarrierRuleRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Module\Inl_shippingcost\Entity\CarrierRule

  prestashop.module.inl_shippingcost.presenter.carrier_rule_presenter:
    class: PrestaShop\Module\Inl_shippingcost\Presenter\CarrierRulePresenter
    
  # Grid services
  inl_shippingcost.grid.definition.factory.carrier_rule:
    class: 'Module\Inl_shippingcost\Grid\Definition\Factory\CarrierRuleGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    
  inl_shippingcost.grid.query_builder.carrier_rule:
    class: 'Module\Inl_shippingcost\Grid\Query\CarrierRuleQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id_shop_group"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.getGroup().share_stock"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'
      - '@prestashop.adapter.legacy.configuration'

  inl_shippingcost.grid.data_provider.carrier_rule:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@inl_shippingcost.grid.query_builder.carrier_rule'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'carrier_rule'

  inl_shippingcost.grid.factory.carrier_rule:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@inl_shippingcost.grid.definition.factory.carrier_rule'
      - '@inl_shippingcost.grid.data_provider.carrier_rule'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
      
  prestashop.module.inl_shippingcost.form.type.carrier_rule_text:
    class: 'Module\Inl_shippingcost\Form\CarrierRuleTextType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }
      
  prestashop.module.inl_shippingcost.form.carrier_rule_text_form_data_provider:
    class: 'Module\Inl_shippingcost\Form\CarrierRuleTextFormDataProvider'
    arguments:
      - '@prestashop.module.inl_shippingcost.form.carrier_rule_text_data_configuration'
      - '@doctrine.orm.entity_manager'
      - Module\Inl_shippingcost\Entity\CarrierRule
      - Module\Inl_shippingcost\Repository\CarrierRuleRepository
      
  prestashop.module.inl_shippingcost.form.carrier_rule_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    public: true
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.module.inl_shippingcost.form.carrier_rule_text_form_data_provider'
      - 'Module\Inl_shippingcost\Form\CarrierRuleTextType'
      - 'CarrierRule'
      
  prestashop.module.inl_shippingcost.form.carrier_rule_text_data_configuration:
    class: Module\Inl_shippingcost\Form\CarrierRuleTextDataConfiguration
    arguments: ['@prestashop.adapter.legacy.configuration']